-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 02:54:07 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ourtrips
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ourtrips` ;

-- -----------------------------------------------------
-- Schema ourtrips
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ourtrips` DEFAULT CHARACTER SET latin1 ;
USE `ourtrips` ;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `username` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `gender` TINYINT(4) NOT NULL,
  `dob` DATETIME NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `address` TEXT NOT NULL,
  `tel` VARCHAR(12) NOT NULL,
  `nationality` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `potrait_img_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `discount`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `discount` ;

CREATE TABLE IF NOT EXISTS `discount` (
  `id` VARCHAR(255) NOT NULL,
  `owner_id` VARCHAR(255) NOT NULL,
  `policy_expression` JSON NOT NULL,
  PRIMARY KEY (`id`, `owner_id`),
  CONSTRAINT `discount_owner_fk`
    FOREIGN KEY (`owner_id`)
    REFERENCES `user` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `driver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `driver` ;

CREATE TABLE IF NOT EXISTS `driver` (
  `id` VARCHAR(255) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `district` VARCHAR(45) NOT NULL,
  `address_line1` TEXT NOT NULL,
  `address_line2` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `emergency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emergency` ;

CREATE TABLE IF NOT EXISTS `emergency` (
  `id` INT(13) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `employee_id` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee` ;

CREATE TABLE IF NOT EXISTS `employee` (
  `id` VARCHAR(255) NOT NULL,
  `department` VARCHAR(255) NOT NULL,
  `role` BINARY(3) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ewallet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ewallet` ;

CREATE TABLE IF NOT EXISTS `ewallet` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `vendor` VARCHAR(255) NOT NULL,
  `balance` INT(11) UNSIGNED NOT NULL,
  `accountNumber` VARCHAR(34) NOT NULL,
  `user_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `ewallet_user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `licence`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licence` ;

CREATE TABLE IF NOT EXISTS `licence` (
  `id` VARCHAR(20) NOT NULL,
  `due_date` DATETIME NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `authority` VARCHAR(255) NOT NULL,
  `driver_id` VARCHAR(255) NOT NULL,
  `approval_status` VARCHAR(45) NOT NULL,
  `approval_due_date` DATETIME NULL DEFAULT NULL,
  `employee_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `licence_driver_fk`
    FOREIGN KEY (`driver_id`)
    REFERENCES `driver` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `licence_employee_fk`
    FOREIGN KEY (`employee_id`)
    REFERENCES `employee` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payment` ;

CREATE TABLE IF NOT EXISTS `payment` (
  `id` INT(12) NOT NULL AUTO_INCREMENT,
  `trip_id` INT(11) NOT NULL,
  `discount_id` VARCHAR(255) NULL DEFAULT NULL,
  `total_amount` INT(12) NOT NULL,
  `amount` INT(12) NOT NULL,
  `from_ewallet_id` INT(11) NOT NULL,
  `to_ewallet_id` INT(11) NOT NULL,
  `luquidation_type` INT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `payment_from_ewallet_fk`
    FOREIGN KEY (`from_ewallet_id`)
    REFERENCES `ewallet` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `payment_to_ewallet_fk`
    FOREIGN KEY (`to_ewallet_id`)
    REFERENCES `ewallet` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `report` ;

CREATE TABLE IF NOT EXISTS `report` (
  `id` INT(13) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `subcategory` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `vehicle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vehicle` ;

CREATE TABLE IF NOT EXISTS `vehicle` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(255) NOT NULL,
  `type` INT(2) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `engine_cap` INT(6) NOT NULL,
  `color` VARCHAR(255) NOT NULL,
  `gross_ton` INT(6) NOT NULL,
  `total_weight` INT(6) NOT NULL,
  `n_passengers` INT(3) NOT NULL,
  `pic_l` BLOB NULL DEFAULT NULL,
  `pic_r` BLOB NULL DEFAULT NULL,
  `pic_f` BLOB NULL DEFAULT NULL,
  `pic_rr` BLOB NULL DEFAULT NULL,
  `approval_status` VARCHAR(8) NOT NULL,
  `approval_due_date` DATETIME NULL DEFAULT NULL,
  `open_price` INT(12) NULL DEFAULT NULL,
  `trip_price` INT(12) NULL DEFAULT NULL,
  `wait_price` INT(12) NULL DEFAULT NULL,
  `driver_id` VARCHAR(255) NOT NULL,
  `employee_id` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `vehicle_driver_fk`
    FOREIGN KEY (`driver_id`)
    REFERENCES `driver` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `vehicle_employee_fk`
    FOREIGN KEY (`employee_id`)
    REFERENCES `employee` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trip` ;

CREATE TABLE IF NOT EXISTS `trip` (
  `id` INT(11) NOT NULL,
  `owner_id` VARCHAR(255) NOT NULL,
  `discount_id` VARCHAR(255) NULL DEFAULT NULL,
  `vehicle_id` INT(11) NULL DEFAULT NULL,
  `payment_id` INT(8) NULL DEFAULT NULL,
  `whole_trip_price` INT(12) NULL DEFAULT NULL,
  `open_price` INT(12) NULL DEFAULT NULL,
  `avg_price` INT(12) NULL DEFAULT NULL,
  `route` JSON NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `trip_discount_fk`
    FOREIGN KEY (`discount_id` , `owner_id`)
    REFERENCES `discount` (`id` , `owner_id`),
  CONSTRAINT `trip_owner_fk`
    FOREIGN KEY (`owner_id`)
    REFERENCES `user` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `trip_vehicle_fk`
    FOREIGN KEY (`vehicle_id`)
    REFERENCES `vehicle` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `trip_review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trip_review` ;

CREATE TABLE IF NOT EXISTS `trip_review` (
  `id` INT(13) NOT NULL,
  `rating` FLOAT(2,1) NOT NULL,
  `improve_category` VARCHAR(255) NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `review` ;

CREATE TABLE IF NOT EXISTS `review` (
  `user_id` VARCHAR(255) NOT NULL,
  `trip_id` INT(11) NOT NULL,
  `review_id` INT(13) NOT NULL,
  PRIMARY KEY (`user_id`, `trip_id`),
  CONSTRAINT `review_emergency_fk`
    FOREIGN KEY (`review_id`)
    REFERENCES `emergency` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `review_report_fk`
    FOREIGN KEY (`review_id`)
    REFERENCES `report` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `review_trip_fk`
    FOREIGN KEY (`trip_id`)
    REFERENCES `trip` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `review_tripreview_fk`
    FOREIGN KEY (`review_id`)
    REFERENCES `trip_review` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `session` ;

CREATE TABLE IF NOT EXISTS `session` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `login_at` DATETIME NOT NULL,
  `token` LONGTEXT NOT NULL,
  `logged_out` TINYINT(4) NOT NULL DEFAULT '0',
  `info` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `session_user_fk`
    FOREIGN KEY (`username`)
    REFERENCES `user` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `share_route_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `share_route_details` ;

CREATE TABLE IF NOT EXISTS `share_route_details` (
  `id` INT(12) NOT NULL AUTO_INCREMENT,
  `trip_id` INT(11) NOT NULL,
  `route` JSON NOT NULL,
  `price` INT(12) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `shareroute_trip_fk`
    FOREIGN KEY (`trip_id`)
    REFERENCES `trip` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
